### ISSUE TITLE
1.21 Mod Compatibility with Bumblezone

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#1]
[crash-2024-06-23_01.33.43-server.txt](https://github.com/user-attachments/files/15937987/crash-2024-06-23_01.33.43-server.txt)

**Comment by MC-Mods-Pete** [comment]
I just uploaded version 1.0.1 that should fix the issue
https://modrinth.com/mod/contagion/version/1.0.1-1.21

**Comment by makumaku1974** [comment]
It is working as intended.
