### ISSUE TITLE
[Bug] The Bug is caused by Armors Restitched Mod 1.21

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#10]
https://github.com/user-attachments/assets/52d885c3-465a-4eb9-a0e4-4b451ec2cc99

**Comment by makumaku1974** [comment]
should i delete my contagion config file? could be causing some corruption code i think.

**Comment by makumaku1974** [comment]
I think this is the main problem since i removed it and it now works like a charm.
https://github.com/SolipIngen/minecraft.armorrestitched/issues/65#issue-2420659176

**Comment by MC-Mods-Pete** [comment]
it seems to me that the mod Armor Restitched changes something that the onApplied method in the class StatusEffect is not called any more. My mod needs this method to work.

**Comment by MC-Mods-Pete** [comment]
I will close this and mark it as "won't fix" for now, because I see the issue with Armor Restitched.

**Comment by makumaku1974** [comment]
I would understand because this is not the Contagion's issue. More like the other mod's issue.
