### ISSUE TITLE
[Mod Support] for Jade. 

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#11]
I think putting out infection probability by % on zombies with Jade would help out for future ideas.

**Comment by MC-Mods-Pete** [comment]
good idea, I will have a look into it :)

**Comment by MC-Mods-Pete** [comment]
I decided against Jade support and added a small HUD-element with the current protection value. Available with version 1.5.0 :)
![Bildschirmfoto vom 2024-12-19 21-58-29](https://github.com/user-attachments/assets/6c039998-816e-45d1-8683-6e96eab398c5)

**Comment by makumaku1974** [comment]
Holy W, I'll try to play Minecraft again soon.
