### ISSUE TITLE
Missing Flesh 1.21

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#13]
The latest contagion 1.21 version 1.2.0 is missing the flesh from zombies.

**Comment by makumaku1974** [comment]
![image](https://github.com/user-attachments/assets/b580d16e-85e0-4a67-aa4d-473ee3485cf1)

**Comment by MC-Mods-Pete** [comment]
I created a new 1.21 game with just Contagion 1.2.0 installed, killed a few zombies and no issues.
![grafik](https://github.com/user-attachments/assets/58bba55e-4a65-4bbf-82d3-49a237c1cad7)

**Comment by makumaku1974** [comment]
could be a bug regarding with the mod Charm... somehow some mods just dont get along with other mods. I would reconsider re testing again since I got a bit ahead of myself.

**Comment by makumaku1974** [comment]
Have you check it with turning on Milk Drinking option? since I turned that on.

**Comment by MC-Mods-Pete** [comment]
just tried with the milk drinking option, still works :)

**Comment by makumaku1974** [comment]
ill be closing this since I'll be using the milk curing method. till I find the cause.

**Comment by makumaku1974** [comment]
What rarity did you put it in percent. It seems like it works on a new instance.

**Comment by MC-Mods-Pete** [comment]
it's set to 5%, so on average you have to kill 20 Zombies for 1 Contagious Flesh.

**Comment by makumaku1974** [comment]
so that's why. Will it affect Looting enchantment soon?

**Comment by MC-Mods-Pete** [comment]
I was also thinking maybe making the value configurable
