### ISSUE TITLE
[Vanilla+] Looting More Contagious Flesh

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#15]
Using Looting enchantment to get more Contagious Flesh.

**Comment by MC-Mods-Pete** [comment]
It's on my ToDo list :)

**Comment by MC-Mods-Pete** [comment]
I would implement it like this:
- 7.5% base change
- per level of looting: 2.5% (leading to a total of 15%, incl. the base chance)
- a drop can be either one or two pieces of flesh

**Comment by makumaku1974** [comment]
that's good for a balanced drop

**Comment by MC-Mods-Pete** [comment]
please check out the latest version 1.4.1
https://modrinth.com/mod/contagion/version/rPbnX4mH

**Comment by MC-Mods-Pete** [comment]
please reopen if needed :)
