### ISSUE TITLE
[Bug] Contagion breaks armor after death. 1.21

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#16]
Dying from the infection destroys the armor after death. Idk why but that's what ive experienced after death.

**Comment by MC-Mods-Pete** [comment]
you are right, bypassing the armor does not work.
Working on a fix...

**Comment by MC-Mods-Pete** [comment]
please check out the latest version 1.4.1
https://modrinth.com/mod/contagion/version/rPbnX4mH

**Comment by MC-Mods-Pete** [comment]
please reopen if you find additional problems :)
