### ISSUE TITLE
[Feature] Disable Milk Curing and Health Levels Compatibility 1.21

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#2]
Adding an optional config modifier that disables Milk Bucket so that Immunity potion is frequently used.

Also, I guess I found a bug that the infection effect doesnt even work anymore. 

![Screenshot 2024-06-30 114815](https://github.com/MC-Mods-Pete/Contagion/assets/129804277/be15e8aa-cd58-4305-b15f-11717a4a3fa8)

**Comment by MC-Mods-Pete** [comment]
thanks for committing the report, did this happen after drinking milk?

**Comment by makumaku1974** [comment]
> thanks for committing the report, did this happen after drinking milk?

No no, it's a different matter. The milk curing is a bit too OP imo.

The bug im actually having is I guess your mod conflicting with Health Levels. Because it looks like it bypasses the health system of that mod. Hence Contagion is having a hard time trying to kill my character i guess?

**Comment by makumaku1974** [comment]
Does it 1 hit the player after Infection drops to 0?

**Comment by MC-Mods-Pete** [comment]
Yes, it deals 1-hit damage

Yeah, milk is quite "annoying", it just removes all effects, no matter what... I will look for a way around that :)

**Comment by MC-Mods-Pete** [comment]
Is your screenshot showing the problem with the more hearts mod?

**Comment by makumaku1974** [comment]
Yes! Unless you want to make compatibility with this mod called Health Levels by SmushyTaco. Could be a lot of work but take your time. Ill wait for the update

**Comment by MC-Mods-Pete** [comment]
Last night I created a first version, that should give the option to disable milk curing and fix the more hearts issue. I will give you that version for testing soon :)

**Comment by makumaku1974** [comment]
fine by me.

**Comment by MC-Mods-Pete** [comment]
Can you please test the following release:
https://modrinth.com/mod/contagion/version/1.0.9-1.21

Please note, this new release needs Cloth Config API and has modmenu integration :)
It has Options to disable Milk and how Totems are handled.

**Comment by MC-Mods-Pete** [comment]
![Bildschirmfoto vom 2024-07-04 00-22-34](https://github.com/MC-Mods-Pete/Contagion/assets/170182225/2f9b30a2-5b71-4ba6-b8ea-c2f24fdcbac7)

**Comment by makumaku1974** [comment]
ill see what i can do.

**Comment by makumaku1974** [comment]
This is better now. Btw i would request a new feature.

**Comment by MC-Mods-Pete** [comment]
Thanks for testing :+1: 

> Btw i would request a new feature

Go ahead, I see what I can do :)
