### ISSUE TITLE
[FEATURE] Missing mobs that infects the player.

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#3]
So i've been experimenting and i realize Zombie Villagers cant infect me yet.

**Comment by MC-Mods-Pete** [comment]
good point...

Please see https://modrinth.com/mod/contagion/version/1.1.0-1.21
(zombie villagers and zombified piglins will now also infect the player)

**Comment by makumaku1974** [comment]
Zombified hoglins could work... just a neat feature

**Comment by MC-Mods-Pete** [comment]
The Zoglin will be in the next release :)

**Comment by MC-Mods-Pete** [comment]
Release 1.1.1 includes the Zoglin as an infection source:
https://modrinth.com/mod/contagion/version/1.1.1-1.21

**Comment by makumaku1974** [comment]
completed
