### ISSUE TITLE
[FEATURE] Turning players into zombies after a successful infection.

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#4]
I think during the walking dead modpack days there was a feature that implemented zombies infecting players that after a successful infection they would too turn into a zombie with loaded weapons and items which the only way to retrieve your items was to kill them. Also, this could be your first special zombie which cannot despawn.

**Comment by MC-Mods-Pete** [comment]
I actually turned this into a mod of it's own
https://www.curseforge.com/minecraft/mc-mods/zombified-player

I just released the first beta version of the mod. It would be very cool if you could have a look and test this new mod as well. :)

**Comment by MC-Mods-Pete** [comment]
It currently spawns a zombified player no matter how the player dies, but that is why it's beta :)

**Comment by MC-Mods-Pete** [comment]
The latest release includes new config options, e.g. to only spawn a Zombie Player if killed by a Zombie :)

**Comment by makumaku1974** [comment]
sorry for the late reply, i've been testing this mod and I think it's already perfect condition. ❤️❤️❤️
