### ISSUE TITLE
[BUG] Shield should fully negate infection since it is attacking the shield.

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#5]
Shield should prevent infection no matter what. I was shocked that it pierced through my shield. The zombie also was not holding any weapon with piercing.

**Comment by MC-Mods-Pete** [comment]
Thanks for your bug report. I just implemented a fix, that will be part of the next release.

**Comment by MC-Mods-Pete** [comment]
can you please check if the issue is fixed with release 1.1.1?
https://modrinth.com/mod/contagion/version/1.1.1-1.21

**Comment by makumaku1974** [comment]
it is resolved now. I'lll be closing this one.
