### ISSUE TITLE
[SUGGESTION] Play sound instead of chat saying "New Infection Prevented".

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#6]
This mod is in good shape now, but the "Infection Prevented" chat provoking is a bit too overused.

![image](https://github.com/user-attachments/assets/7b14b3a0-3f9f-4df8-a4ea-ab67f8df63f1)

Players could also find this bit annoying but to improve it. Basically when they get attacked by Zombies they hear an immunity sound. (ofc when they have the immunity effect on.)

Also, for the sounds to be less annoying it can only play for about 1 to 2 times but not consecutive. For Combat Purposes

**Comment by MC-Mods-Pete** [comment]
I like that idea :)

Question is, what does Immunity sound like... :)

**Comment by makumaku1974** [comment]
> I like that idea :)
> 
> Question is, what does Immunity sound like... :)

I found this sampleS site and it's not much but could be useful.
https://mixkit.co/free-sound-effects/transition/

**Comment by MC-Mods-Pete** [comment]
please check out release 1.2.0 https://modrinth.com/mod/contagion/version/1.2.0-1.21
