### ISSUE TITLE
[COMPATIBILITY] with Penomior.

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#7]
I have to bump this to you because the Evasion skill from Penomior still infects the player regardless.

**Comment by makumaku1974** [comment]
https://github.com/MrSypz/Penomior/issues/6#issuecomment-2229951991

**Comment by MC-Mods-Pete** [comment]
thanks for pointing that out, I will have a look

**Comment by MrSypz** [comment]
you don't need to do it anymore, I already inject my method before callback event happen 👍I forgot fabric have this callback too 🤣

**Comment by makumaku1974** [comment]
> you don't need to do it anymore, I already inject my method before callback event happen 👍I forgot fabric have this callback too 🤣

let me check again. okay it's fixed, No need to fix it Pete.

**Comment by MC-Mods-Pete** [comment]
Thanks for the info, I already did a rework of my stuff ;)
Because there is some truth to Contagion being a bit op at times.

In my rework I now inject my stuff into the tryAttack methods, so I can check if the player was actually hurt :)

**Comment by makumaku1974** [comment]
> you don't need to do it anymore, I already inject my method before callback event happen 👍I forgot fabric have this callback too 🤣

you missed out two mobs btw. Drowned and Husk still infects player on evasion attacks.
