### ISSUE TITLE
[Bug] Contagion. 1.21

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#8]
Issues: 

I tested my modpack and somehow after getting an Infection (Which the infection didn't last for 600 seconds but minimum) died in a short manner of time. I think it skipped the process for 600 seconds and once im dead. When Zombies hit me and get an infection i die quickly. It like somehow the infection did not reset.

Could you tell me what the issue is perhaps because it is starting to be like with the previous modpack i was trying to develop.
Logs: https://mclo.gs/vXqe1ie

**Comment by makumaku1974** [comment]
This is btw caused by Slow Your Roll mod.

**Comment by makumaku1974** [comment]
Please check this first before fixing your mod. Slow Your Roll is overwriting mods like Pale Mod which I added for when you eat Rotten Flesh you burn into sunlight (Not literally burn but get damaged only).

**Comment by MC-Mods-Pete** [comment]
I was not able to reproduce this yet.
I created a fresh 1.21 instance and installed Contagion and Slow Your Roll.
And the countdown from 600 seconds to 0 works like expected.

**Comment by makumaku1974** [comment]
Now that is weird.

**Comment by makumaku1974** [comment]
have you tried it with pale?

**Comment by makumaku1974** [comment]
This is the list for now. I guess I have to redo it then again.
![image](https://github.com/user-attachments/assets/896336cb-a657-4e23-896b-c2025a24eaec)
![image](https://github.com/user-attachments/assets/79ecf7ae-940c-4539-aebc-9fcbc1f81fa4)
![image](https://github.com/user-attachments/assets/ebc68f9a-c584-4e4a-a507-a247d5202668)
![image](https://github.com/user-attachments/assets/2649fb26-4956-4015-b998-7712dc629be2)
![image](https://github.com/user-attachments/assets/f980517e-6843-4499-bf0c-cd48b4e9201c)
![image](https://github.com/user-attachments/assets/dd74aeca-be52-4c49-b5d6-41f5d806395a)

**Comment by makumaku1974** [comment]
I'll close this issue now I think i fixed it and creating a closing point.
