### ISSUE TITLE
[Bug] Penomior and Contagion

### ISSUE THREAD

**Issue by makumaku1974** [MC-Mods-Pete/Contagion#9]
The evasion mechanic still gets fumbled by Contagion. Seemingly, your mod still infects the player despite evasion being high tier.

![image](https://github.com/user-attachments/assets/7cad7039-dd19-4491-b26d-58df155f8f58)
![image](https://github.com/user-attachments/assets/6983d212-a23e-46da-8529-e9062508fa29)

**Comment by MC-Mods-Pete** [comment]
The next release should fix this. I rewrote Contagion so it only fires if the call of the damage method returns true (the player actually took damage).
It's already in the git repo, but not released yet.

**Comment by makumaku1974** [comment]
That's actually great to hear from you since that this mod is what I'm waiting for. Now, this is even great with Vic's Point Blank and I could think of a great animation for using Immunity potion.

**Comment by MC-Mods-Pete** [comment]
reference to issue #7

**Comment by MC-Mods-Pete** [comment]
please check out release 1.2.0 https://modrinth.com/mod/contagion/version/1.2.0-1.21

**Comment by makumaku1974** [comment]
it's fixed now. I'll be closing this one now.
